from .embedding_loader import (
    NODE_CLASS_MAPPINGS as EMBEDDING_LOADER_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as EMBEDDING_LOADER_DISPLAY_NAME_MAPPINGS,
)
from .simple_nodes import (
    NODE_CLASS_MAPPINGS as SIMPLE_NODES_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SIMPLE_NODES_DISPLAY_NAME_MAPPINGS,
)

WEB_DIRECTORY = "./scripts"

NODE_CLASS_MAPPINGS = {
    **EMBEDDING_LOADER_CLASS_MAPPINGS,
    **SIMPLE_NODES_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **EMBEDDING_LOADER_DISPLAY_NAME_MAPPINGS,
    **SIMPLE_NODES_DISPLAY_NAME_MAPPINGS,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
