from .embedding_loader import (
    NODE_CLASS_MAPPINGS as EMBEDDING_LOADER_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as EMBEDDING_LOADER_DISPLAY_NAME_MAPPINGS,
)
from .identity import (
    NODE_CLASS_MAPPINGS as IDENTITY_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as IDENTITY_DISPLAY_NAME_MAPPINGS,
)
from .simple_switch import (
    NODE_CLASS_MAPPINGS as SIMPLE_SWITCH_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SIMPLE_SWITCH_DISPLAY_NAME_MAPPINGS,
)
from .stateful_multiline import (
    NODE_CLASS_MAPPINGS as STATEFUL_MULTILINE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as STATEFUL_MULTILINE_DISPLAY_NAME_MAPPINGS,
)

WEB_DIRECTORY = "./scripts"

NODE_CLASS_MAPPINGS = {
    **EMBEDDING_LOADER_CLASS_MAPPINGS,
    **IDENTITY_CLASS_MAPPINGS,
    **SIMPLE_SWITCH_CLASS_MAPPINGS,
    **STATEFUL_MULTILINE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **EMBEDDING_LOADER_DISPLAY_NAME_MAPPINGS,
    **IDENTITY_DISPLAY_NAME_MAPPINGS,
    **SIMPLE_SWITCH_DISPLAY_NAME_MAPPINGS,
    **STATEFUL_MULTILINE_DISPLAY_NAME_MAPPINGS,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
